/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import java.text.DecimalFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.temporal.ChronoUnit;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import model.DTO.DichVuSuDung;
import model.DTO.PhongEmbed;
import model.DTO.PhongEmbed_HoaDon;

/**
 *
 * @author Admin
 */


public class ChiTietHoaDon_DanhSachThanhToan extends javax.swing.JPanel {

    public static DecimalFormat df = new DecimalFormat("#,##0");

    /**
     * Creates new form ChiTietHoaDon_DanhSachThanhToan
     *
     * @param p
     */
    public ChiTietHoaDon_DanhSachThanhToan(PhongEmbed_HoaDon p, List<DichVuSuDung> list_dv) {
        initComponents();
        ma_phong.setText(String.valueOf("Phòng " + p.getMaPhong()));

        LocalDate localDateFrom = p.getNgayNhan().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        LocalDate localDateTo = setThoiGian0(new Date()).toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        long daysBetween = ChronoUnit.DAYS.between(localDateFrom, localDateTo);
        int tienPhong = (int)daysBetween*p.getDonGia();
        int tiendv = 0;
        for(DichVuSuDung dv : list_dv){
            tiendv+= dv.getDonGia() * dv.getSoLuong();
        }
        int tongTien = tienPhong + tiendv;

        so_tien_tra.setText(df.format(tongTien) + " VNĐ");
    }
    
    public Date setThoiGian0(Date date) {

        Calendar calendar = Calendar.getInstance();
        calendar.setTime(date); // Đặt ngày hiện tại
        calendar.set(Calendar.HOUR_OF_DAY, 0);
        calendar.set(Calendar.MINUTE, 0);
        calendar.set(Calendar.SECOND, 0);
        calendar.set(Calendar.MILLISECOND, 0);
        return calendar.getTime();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ma_phong = new javax.swing.JLabel();
        so_tien_tra = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));

        ma_phong.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        ma_phong.setForeground(new java.awt.Color(255, 209, 84));
        ma_phong.setText("Standard 302");

        so_tien_tra.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        so_tien_tra.setForeground(new java.awt.Color(255, 209, 84));
        so_tien_tra.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        so_tien_tra.setText("1,000,000");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ma_phong)
                .addGap(18, 18, 18)
                .addComponent(so_tien_tra, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ma_phong)
                    .addComponent(so_tien_tra))
                .addContainerGap(15, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ma_phong;
    private javax.swing.JLabel so_tien_tra;
    // End of variables declaration//GEN-END:variables
}
