/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;
import javax.swing.*;
import java.awt.*;

/**
 *
 * @author Admin
 */

public class CirclePanel_Atatar extends javax.swing.JPanel {

    public CirclePanel_Atatar() {
        // Đặt JPanel trong suốt
        setOpaque(false);
    }
//
//    @Override
//    protected void paintComponent(Graphics g) {
//        super.paintComponent(g);
//        Graphics2D g2d = (Graphics2D) g;
//
//        // Bật chế độ khử răng cưa
//        g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
//
//        // Lấy kích thước panel
//        int width = getWidth();
//        int height = getHeight();
//
//        // Tính toán đường kính của hình tròn
//        int diameter = Math.min(width, height);
//
//        // Chọn màu cho hình tròn
//        g2d.setColor(Color.BLUE);
//
//        // Vẽ hình tròn
//        g2d.fillOval((width - diameter) / 2, (height - diameter) / 2, diameter, diameter);
//    }
    
    @Override
protected void paintComponent(Graphics g) {
    super.paintComponent(g);
    Graphics2D g2d = (Graphics2D) g;

    // Bật chế độ khử răng cưa
    g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

    // Lấy kích thước panel
    int width = getWidth();
    int height = getHeight();

    // Tính toán đường kính của hình tròn
    int diameter = Math.min(width, height);

    // Chọn màu cho hình tròn
    g2d.setColor(Color.BLUE);

    // Vẽ hình tròn
    g2d.fillOval((width - diameter) / 2, (height - diameter) / 2, diameter, diameter);

    
    // Thêm border cho hình tròn
    g2d.setColor(new Color(255, 209, 84)); // Màu của border
    g2d.setStroke(new BasicStroke(2)); // Độ dày của border (3 pixel)
    g2d.drawOval((width - diameter) / 2, (height - diameter) / 2, diameter, diameter);
}

    @Override
    public Dimension getPreferredSize() {
        // Đảm bảo Panel có tỷ lệ vuông
        return new Dimension(50, 50);
    }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}





