/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

import Functions.ImageScale;
import com.mongodb.client.MongoDatabase;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.image.ImageObserver;
import java.awt.image.ImageProducer;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import keeptoo.KGradientPanel;
import model.DAO.DichVuDAO;
import model.DAO.TienNghiDAO;
import model.DTO.DichVu;
import model.MongoDBConnection;
import test.convertImage;

/**
 *
 * @author Admin
 */
public class NhanVien_DichVu_GUI extends javax.swing.JInternalFrame {

    /**
     * Creates new form LeTan_DatPhong_GUI
     */
    private MongoDBConnection connection = new MongoDBConnection();
    private MongoDatabase database = connection.getDatabase();
    private ArrayList<KGradientPanel> list_btn = new ArrayList<KGradientPanel>();
    
    
    private DichVuDAO dichVuDAO = new DichVuDAO(database);
    
    private byte[] hinhAnh = null;
//    private String filePath = "";
    public NhanVien_DichVu_GUI() {
        initComponents();
        
        
        list_btn.add(btn_them);
        list_btn.add(btn_Sua);
        list_btn.add(btn_Xoa);
        list_btn.add(btn_Tim);
        list_btn.add(btn_chonAnh);
        
        list_btn.forEach((element) -> {
            element.addMouseListener(new MouseListener() {
                @Override
                public void mouseClicked(MouseEvent e) {
//                    throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
                }
               
                @Override
                public void mousePressed(MouseEvent e) {
                        
//                    throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
                }

                @Override
                public void mouseReleased(MouseEvent e) {
//                    throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
                }

                @Override
                public void mouseEntered(MouseEvent e) {
                    element.setkStartColor(new java.awt.Color(255, 225, 27));
                    element.setkEndColor(new java.awt.Color(255, 222, 89));
                    element.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 1));
                    element.setBorder(null);
                }

                @Override
                public void mouseExited(MouseEvent e) {
                    element.setkStartColor(new java.awt.Color(225, 176, 27));
                    element.setkEndColor(new java.awt.Color(255, 222, 89));
                    element.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 1));
                    element.setBorder(null);
                   
                }
            });
        })
        ;
        
        
        
        
        this.setBorder(BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ThongTinDichVu = new javax.swing.JPanel();
        tenDichVu = new javax.swing.JLabel();
        moTa = new javax.swing.JLabel();
        donGia = new javax.swing.JLabel();
        txt_DichVu = new javax.swing.JTextField();
        txt_MoTa = new javax.swing.JTextField();
        txtDonGia = new javax.swing.JTextField();
        donGia1 = new javax.swing.JLabel();
        btn_chonAnh = new keeptoo.KGradientPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btn_Tim = new keeptoo.KGradientPanel();
        jLabel18 = new javax.swing.JLabel();
        btn_them = new keeptoo.KGradientPanel();
        jLabel15 = new javax.swing.JLabel();
        btn_Xoa = new keeptoo.KGradientPanel();
        jLabel17 = new javax.swing.JLabel();
        btn_Sua = new keeptoo.KGradientPanel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        label_Anh = new javax.swing.JLabel();
        Backgroup = new javax.swing.JLabel();

        setName("page_DichVu"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1283, 830));
        getContentPane().setLayout(null);

        jPanel1.setPreferredSize(new java.awt.Dimension(1283, 803));
        jPanel1.setLayout(null);

        ThongTinDichVu.setBackground(new java.awt.Color(0, 0, 0));
        ThongTinDichVu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 209, 84), 2));
        ThongTinDichVu.setOpaque(false);

        tenDichVu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tenDichVu.setForeground(new java.awt.Color(255, 255, 255));
        tenDichVu.setText("Tên dịch vụ");

        moTa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        moTa.setForeground(new java.awt.Color(255, 255, 255));
        moTa.setText("Mô tả");

        donGia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        donGia.setForeground(new java.awt.Color(255, 255, 255));
        donGia.setText("Đơn giá");

        txt_DichVu.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txt_DichVu.setPreferredSize(new java.awt.Dimension(64, 32));

        txt_MoTa.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txt_MoTa.setPreferredSize(new java.awt.Dimension(64, 32));

        txtDonGia.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtDonGia.setPreferredSize(new java.awt.Dimension(64, 32));
        txtDonGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDonGiaActionPerformed(evt);
            }
        });

        donGia1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        donGia1.setForeground(new java.awt.Color(255, 255, 255));
        donGia1.setText("Hình ảnh");

        btn_chonAnh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_chonAnh.setkEndColor(new java.awt.Color(255, 222, 89));
        btn_chonAnh.setkGradientFocus(250);
        btn_chonAnh.setkStartColor(new java.awt.Color(225, 176, 27));
        btn_chonAnh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_chonAnhMouseClicked(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Chọn ảnh");
        jLabel19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout btn_chonAnhLayout = new javax.swing.GroupLayout(btn_chonAnh);
        btn_chonAnh.setLayout(btn_chonAnhLayout);
        btn_chonAnhLayout.setHorizontalGroup(
            btn_chonAnhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_chonAnhLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        btn_chonAnhLayout.setVerticalGroup(
            btn_chonAnhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout ThongTinDichVuLayout = new javax.swing.GroupLayout(ThongTinDichVu);
        ThongTinDichVu.setLayout(ThongTinDichVuLayout);
        ThongTinDichVuLayout.setHorizontalGroup(
            ThongTinDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThongTinDichVuLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(ThongTinDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tenDichVu)
                    .addComponent(donGia)
                    .addComponent(txtDonGia, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                    .addComponent(txt_DichVu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(ThongTinDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ThongTinDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ThongTinDichVuLayout.createSequentialGroup()
                            .addComponent(moTa, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(303, 303, 303))
                        .addGroup(ThongTinDichVuLayout.createSequentialGroup()
                            .addGroup(ThongTinDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(donGia1)
                                .addComponent(txt_MoTa, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addContainerGap()))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ThongTinDichVuLayout.createSequentialGroup()
                        .addComponent(btn_chonAnh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))))
        );
        ThongTinDichVuLayout.setVerticalGroup(
            ThongTinDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThongTinDichVuLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(ThongTinDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ThongTinDichVuLayout.createSequentialGroup()
                        .addComponent(moTa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_MoTa, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                    .addGroup(ThongTinDichVuLayout.createSequentialGroup()
                        .addComponent(tenDichVu)
                        .addGap(4, 4, 4)
                        .addComponent(txt_DichVu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(ThongTinDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(ThongTinDichVuLayout.createSequentialGroup()
                        .addComponent(donGia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDonGia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(ThongTinDichVuLayout.createSequentialGroup()
                        .addComponent(donGia1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_chonAnh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33))
        );

        jPanel1.add(ThongTinDichVu);
        ThongTinDichVu.setBounds(70, 100, 760, 220);

        jLabel14.setBackground(new java.awt.Color(255, 209, 84));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 209, 84));
        jLabel14.setText("Thông tin dịch vụ");
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel14);
        jLabel14.setBounds(70, 50, 250, 32);

        btn_Tim.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_Tim.setkEndColor(new java.awt.Color(255, 222, 89));
        btn_Tim.setkGradientFocus(250);
        btn_Tim.setkStartColor(new java.awt.Color(225, 176, 27));
        btn_Tim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_TimMouseClicked(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Tìm");
        jLabel18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout btn_TimLayout = new javax.swing.GroupLayout(btn_Tim);
        btn_Tim.setLayout(btn_TimLayout);
        btn_TimLayout.setHorizontalGroup(
            btn_TimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_TimLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                .addContainerGap())
        );
        btn_TimLayout.setVerticalGroup(
            btn_TimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_TimLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(btn_Tim);
        btn_Tim.setBounds(550, 350, 140, 40);

        btn_them.setkEndColor(new java.awt.Color(255, 222, 89));
        btn_them.setkGradientFocus(250);
        btn_them.setkStartColor(new java.awt.Color(225, 176, 27));
        btn_them.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_themMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_themMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_themMouseExited(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Thêm");
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout btn_themLayout = new javax.swing.GroupLayout(btn_them);
        btn_them.setLayout(btn_themLayout);
        btn_themLayout.setHorizontalGroup(
            btn_themLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        btn_themLayout.setVerticalGroup(
            btn_themLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_themLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(btn_them);
        btn_them.setBounds(70, 350, 140, 40);

        btn_Xoa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_Xoa.setkEndColor(new java.awt.Color(255, 222, 89));
        btn_Xoa.setkGradientFocus(250);
        btn_Xoa.setkStartColor(new java.awt.Color(225, 176, 27));
        btn_Xoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_XoaMouseClicked(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Xóa");
        jLabel17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout btn_XoaLayout = new javax.swing.GroupLayout(btn_Xoa);
        btn_Xoa.setLayout(btn_XoaLayout);
        btn_XoaLayout.setHorizontalGroup(
            btn_XoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
        );
        btn_XoaLayout.setVerticalGroup(
            btn_XoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_XoaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(btn_Xoa);
        btn_Xoa.setBounds(390, 350, 140, 40);

        btn_Sua.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_Sua.setkEndColor(new java.awt.Color(255, 222, 89));
        btn_Sua.setkGradientFocus(250);
        btn_Sua.setkStartColor(new java.awt.Color(225, 176, 27));
        btn_Sua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_SuaMouseClicked(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Sửa");
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout btn_SuaLayout = new javax.swing.GroupLayout(btn_Sua);
        btn_Sua.setLayout(btn_SuaLayout);
        btn_SuaLayout.setHorizontalGroup(
            btn_SuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
        );
        btn_SuaLayout.setVerticalGroup(
            btn_SuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_SuaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(btn_Sua);
        btn_Sua.setBounds(230, 350, 140, 40);

        JTableHeader header = jTable1.getTableHeader();
        header.setPreferredSize(new Dimension(header.getPreferredSize().width, 30));
        header.setFont(new Font("Arial", Font.BOLD, 15));
        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jTable1.setModel(duaDataVaoModel(dichVuDAO.getAllDichVu()));
        jTable1.setRowHeight(30);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(70, 410, 1120, 360);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 209, 84)));

        label_Anh.setBackground(new java.awt.Color(255, 255, 51));
        label_Anh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_AnhMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(label_Anh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 289, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(label_Anh, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(890, 100, 300, 280);

        Backgroup.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Backgroup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Backgroup.png"))); // NOI18N
        Backgroup.setPreferredSize(new java.awt.Dimension(1283, 803));
        jPanel1.add(Backgroup);
        Backgroup.setBounds(10, 0, 1283, 803);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1283, 803);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    static DefaultTableModel duaDataVaoModel(List<DichVu> list_DichVu) {
        
        
        Object[][] object = new Object[list_DichVu.size()][4];
        for(int i = 0; i < object.length; i++) {
            DichVu x = list_DichVu.get(i);
            object[i] = new Object[]{
                x.getMaDV(), x.getTenDV(), x.getMoTa(), x.getDonGia()
            };
            System.out.println(object[i][0]);
            System.out.println(object[i][1]);
            System.out.println(object[i][2]);
            System.out.println(object[i][3]);
        }
        String[] table_header = new String [] {
                "Mã dịch vụ", "Tên dịch vụ", "Mô tả", "Đơn giá"
        };
        
        return new DefaultTableModel(object, table_header);
        
    }
    
    private void btn_themMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_themMouseClicked
        // TODO add your handling code here:
        try {
            if(txt_DichVu.getText().isBlank()) {
//                JOptionPane.showMessageDialog(this, "Chưa nhập tên dịch vụ!", "Trống dữ liệu", JOptionPane.ERROR_MESSAGE);
                throw new Exception("Chưa nhập tên dịch vụ!");
            }
            if(txt_MoTa.getText().isBlank()) {
//                JOptionPane.showMessageDialog(this, "Chưa nhập mô tả dịch vụ!", "Trống dữ liệu", JOptionPane.ERROR_MESSAGE);
                throw new Exception("Chưa nhập mô tả dịch vụ!");
            }
            if(txtDonGia.getText().isBlank()) {
//                JOptionPane.showMessageDialog(this, "Chưa nhập đơn giá dịch vụ!", "Trống dữ liệu", JOptionPane.ERROR_MESSAGE);
                throw new Exception("Chưa nhập đơn giá dịch vụ!");
            }
            if(hinhAnh == null) {
                throw new Exception("Chưa chọn ảnh dịch vụ!");
            }
//            if(txtHinhAnh.getText().isBlank()) {
//                JOptionPane.showMessageDialog(this, "Chưa chọn hình ảnh dịch vụ!", "Trống dữ liệu", JOptionPane.ERROR_MESSAGE);
//                throw new Exception("Chưa nhập đơn giá dịch vụ!");
//            }
            String tenDichVu = txt_DichVu.getText();
            
            if(dichVuDAO.timDichVu(tenDichVu) != null) {
//                JOptionPane.showMessageDialog(this, "Đã có dịch vụ có tên " + tenDichVu, "Trùng dữ liệu", JOptionPane.ERROR_MESSAGE);
                throw new ExceptionInInitializerError("Trùng dữ liệu");
            }
            
            int maDichVu = dichVuDAO.getAllDichVu().getLast().getMaDV() + 1;
            String moTaDichVu = txt_MoTa.getText();
            int donGia = Integer.parseInt(txtDonGia.getText());
            
            byte[] img = hinhAnh;
            for(byte x: hinhAnh) {
                System.out.print(x);
            }
            //Tạo ra một dịch vụ mới
            DichVu x = new DichVu(maDichVu, tenDichVu, moTaDichVu, donGia, hinhAnh);
            //Đưa dữ liệu vào database
            dichVuDAO.createDichVu(x);
            
            
            //Reset lại dữ liệu trong table
            
            
            //Đưa data vào table 
            jTable1.setModel(duaDataVaoModel(dichVuDAO.getAllDichVu()));
            
            txt_DichVu.setText("");
            txt_MoTa.setText("");
//            hinhAnh = null;
            label_Anh.setIcon(null);
            txt_DichVu.setEnabled(true);
            
            
        } catch(ArithmeticException ar) {
            JOptionPane.showMessageDialog(this, "Đơn giá chỉ được là số thực", "Dữ liệu bị sai", JOptionPane.ERROR_MESSAGE);
        
        }catch (ExceptionInInitializerError e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Trùng dữ liệu", JOptionPane.ERROR_MESSAGE);
        }
        catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Dữ liệu bị thiếu", JOptionPane.ERROR_MESSAGE);
        }
        
        
        

    }//GEN-LAST:event_btn_themMouseClicked

    private void btn_themMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_themMouseEntered
        // TODO add your handling code here:
        btn_them.setkStartColor(new java.awt.Color(255, 225, 27));
        btn_them.setkEndColor(new java.awt.Color(255, 222, 89));
        btn_them.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 1));
        btn_them.setBorder(null);

    }//GEN-LAST:event_btn_themMouseEntered

    private void btn_themMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_themMouseExited
        // TODO add your handling code here:
        btn_them.setkStartColor(new java.awt.Color(225, 176, 27));
        btn_them.setkEndColor(new java.awt.Color(255, 222, 89));
        btn_them.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 1));
        btn_them.setBorder(null);
    }//GEN-LAST:event_btn_themMouseExited

    private void txtDonGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDonGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDonGiaActionPerformed

    private void btn_chonAnhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_chonAnhMouseClicked
        // TODO add your handling code here:
        JFileChooser frame_chonAnh = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("File ảnh", "png", "jpg", "jpeg", "gif");
        frame_chonAnh.setFileFilter(filter);
        frame_chonAnh.setAcceptAllFileFilterUsed(false);
        
        
        int returnValue = frame_chonAnh.showOpenDialog(null);
        if(returnValue == JFileChooser.APPROVE_OPTION) {
            //Đường dẫn của file
            String filePath = frame_chonAnh.getSelectedFile().getPath();
            
            ImageIcon icon = new ImageScale().load(filePath, label_Anh.getWidth(), label_Anh.getHeight());
            
            try {
                hinhAnh = new convertImage().convertImageToBinary(filePath);
            } catch (IOException ex) {
                Logger.getLogger(NhanVien_DichVu_GUI.class.getName()).log(Level.SEVERE, null, ex);
            }            
            
            label_Anh.setIcon(icon);
            
//            txt_DichVu.setEnabled(false);
            
        }
        
    }//GEN-LAST:event_btn_chonAnhMouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        
        if(row != -1) {
            String tenDV = jTable1.getModel().getValueAt(row, 1).toString();
            
            DichVu x = dichVuDAO.timDichVu(tenDV);
//            System.out.println(x.toString());
//            System.out.println(x.getHinhAnh());
            txt_DichVu.setText(x.getTenDV());
            txt_MoTa.setText(x.getMoTa());
            txtDonGia.setText(Integer.toString(x.getDonGia()));
            hinhAnh = x.getHinhAnh();
            ImageIcon icon = new ImageScale().load1(new ImageIcon(hinhAnh), label_Anh.getWidth(), label_Anh.getHeight());

            System.out.println("Không gặp lỗi");
            label_Anh.setIcon(icon);
            
//            txt_DichVu.setEnabled(false);
            
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void btn_SuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SuaMouseClicked
        // TODO add your handling code here:
        try {
            
            if(jTable1.getSelectedRow() != -1) {
                String tenDichVu = txt_DichVu.getText();
                DichVu x = dichVuDAO.timDichVu(tenDichVu);
                System.out.println(x.toString());
                int maDV = x.getMaDV();
                String moTaDV = txt_MoTa.getText();
                int donGia = Integer.parseInt(txtDonGia.getText());
                byte[] hinhAnh = this.hinhAnh;
                System.out.println("Trên label" + String.format("%d %s %d", maDV, moTaDV, donGia));
                DichVu y = new DichVu(maDV, moTaDV, moTaDV, donGia, hinhAnh);
                
                dichVuDAO.suaDichVu(x, y);
//                System.out.println(y.toString());
                jTable1.setModel(duaDataVaoModel(dichVuDAO.getAllDichVu()));
                                
//                txt_DichVu.setEnabled(true);
                txt_DichVu.setText("");
                txt_MoTa.setText("");
                txtDonGia.setText("");
                label_Anh.setIcon(null);
                
            } else {
                throw new Exception("Chưa chọn dịch vụ để sửa đổi");
            }
        }
        catch (ArithmeticException e) {
            JOptionPane.showMessageDialog(this, "Đơn giá chỉ là số thực", "Lỗi dữ liệu", JOptionPane.ERROR_MESSAGE);
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Lỗi dữ liệu", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btn_SuaMouseClicked

    private void btn_XoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_XoaMouseClicked
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        
        if(row != -1) {
//            int maDV = Integer.parseInt(jTable1.getModel().getValueAt(row, 0).toString());
            String tenDV = jTable1.getModel().getValueAt(row, 1).toString();
//            String moTa = jTable1.getModel().getValueAt(row, 2).toString();
//            int donGia = Integer.parseInt(jTable1.getModel().getValueAt(row, 3).toString());

            DichVu x = dichVuDAO.timDichVu(tenDV);
            
            dichVuDAO.xoaDichVu(x);
            
            jTable1.setModel(duaDataVaoModel(dichVuDAO.getAllDichVu()));
        }
        
    }//GEN-LAST:event_btn_XoaMouseClicked

    private void btn_TimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_TimMouseClicked
        // TODO add your handling code here:
//        String tenDV = txt_DichVu.getText();
//        DichVu x = dichVuDAO.timDichVu(tenDV);
//        jTable1.setRowSelectionInterval(WIDTH, WIDTH);
        String tenDV = txt_DichVu.getText();
        if(tenDV.equals("")) {
            JOptionPane.showMessageDialog(this, "Chưa nhập tên dịch vụ cần tìm", "Chưa nhập dữ liệu", JOptionPane.ERROR_MESSAGE);
        }
        
        DichVu x = dichVuDAO.timDichVu(tenDV);
        
        int viTriCuaX = dichVuDAO.getAllDichVu().indexOf(x);
        
        if(viTriCuaX != -1) {
            jTable1.setRowSelectionInterval(viTriCuaX, viTriCuaX);
            
            hinhAnh = x.getHinhAnh();
        } else {
            JOptionPane.showMessageDialog(this, "Không có dịch vụ có tên " + tenDV, "Không tìm thấy dữ liệu", JOptionPane.ERROR_MESSAGE);
        }

        
    }//GEN-LAST:event_btn_TimMouseClicked

    private void label_AnhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_AnhMouseClicked
        // TODO add your handling code here:
        System.out.println(label_Anh.getIcon());
    }//GEN-LAST:event_label_AnhMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Backgroup;
    private javax.swing.JPanel ThongTinDichVu;
    private keeptoo.KGradientPanel btn_Sua;
    private keeptoo.KGradientPanel btn_Tim;
    private keeptoo.KGradientPanel btn_Xoa;
    private keeptoo.KGradientPanel btn_chonAnh;
    private keeptoo.KGradientPanel btn_them;
    private javax.swing.JLabel donGia;
    private javax.swing.JLabel donGia1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel label_Anh;
    private javax.swing.JLabel moTa;
    private javax.swing.JLabel tenDichVu;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txt_DichVu;
    private javax.swing.JTextField txt_MoTa;
    // End of variables declaration//GEN-END:variables
}
