/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

import Functions.ImageScale;
import java.awt.Dimension;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import model.DAO.DonDatPhongDAO;
import model.DTO.NhanVien;
import model.MongoDBConnection;
import org.jfree.chart.ChartPanel;

/**
 *
 * @author Admin
 */
public class QuanLy_DoanhThu_GUI extends javax.swing.JInternalFrame {

    private NhanVien nhanVien_DangSuDung;

    /**
     * Creates new form LeTan_DatPhong_GUI
     */
    private void addChartToScrollPane(JPanel panel) {
        chartPanel.add(panel);
        chartPanel.revalidate(); // Cập nhật lại layout
        chartPanel.repaint(); // Vẽ lại panel
    }

    public QuanLy_DoanhThu_GUI(NhanVien nhanVien_DangSuDung) {
        this.nhanVien_DangSuDung = nhanVien_DangSuDung;
        initComponents();

        cb_TheoNam.removeAllItems();
        cb_TheoNam.addItem(null);
        for (int i : new DonDatPhongDAO(MongoDBConnection.getDatabase()).getYearsByTrangThaiHoanThanh()) {
            cb_TheoNam.addItem(String.format("%s", i));
        }
        
        cb_TheoQuy.removeAllItems();
        cb_TheoQuy.addItem(null);
        cb_TheoQuy.addItem("1");
        cb_TheoQuy.addItem("2");
        cb_TheoQuy.addItem("3");
        cb_TheoQuy.addItem("4");
        cb_TheoNam.setSelectedItem(null);
        cb_TheoQuy.setSelectedItem(null);
        
        Date today = new Date();
        Calendar cal = Calendar.getInstance();
        cal.setTime(today);

        // Đặt ngày bắt đầu là ngày đầu tháng
        cal.set(Calendar.DAY_OF_MONTH, 1);
        txt_TuNgay.setDate(cal.getTime());

        // Đặt ngày kết thúc là ngày hiện tại
        txt_DenNgay.setDate(today);

        jLabel6.setText(this.nhanVien_DangSuDung.getTenNhanVien());
        ImageScale.setCircularImage(label_Avatar, new ImageScale().getScaledImage1(50, 50, new ImageIcon(nhanVien_DangSuDung.getAnhDaiDien())));
        ddpDAO = new DonDatPhongDAO(MongoDBConnection.getDatabase());
        chartPanel = new JPanel();
        chartPanel.setLayout(new BoxLayout(chartPanel, BoxLayout.Y_AXIS)); // Đặt layout dọc cho container
        ScrollChart.setViewportView(chartPanel);

        this.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);

        updateBieuDo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ThongTinDat = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_TuNgay = new com.toedter.calendar.JDateChooser();
        txt_DenNgay = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btn_ThongKe = new keeptoo.KGradientPanel();
        btnThongKe = new javax.swing.JLabel();
        ThongTinDat1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cb_TheoQuy = new javax.swing.JComboBox<>();
        cb_TheoNam = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        panel_ThongKeDoanhThu = new javax.swing.JPanel();
        ScrollChart = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        circlePanel1 = new GUI.CirclePanel_Atatar();
        label_Avatar = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        Backgroup = new javax.swing.JLabel();

        setName("page_DoanhThu"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1283, 830));

        jPanel1.setPreferredSize(new java.awt.Dimension(1283, 803));
        jPanel1.setLayout(null);

        ThongTinDat.setBackground(new java.awt.Color(0, 0, 0));
        ThongTinDat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 209, 84), 2));
        ThongTinDat.setOpaque(false);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Từ ngày");

        txt_TuNgay.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txt_TuNgayPropertyChange(evt);
            }
        });

        txt_DenNgay.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txt_DenNgayPropertyChange(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Đến ngày");

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_MuiTen.png"))); // NOI18N
        jLabel21.setText("jLabel21");

        javax.swing.GroupLayout ThongTinDatLayout = new javax.swing.GroupLayout(ThongTinDat);
        ThongTinDat.setLayout(ThongTinDatLayout);
        ThongTinDatLayout.setHorizontalGroup(
            ThongTinDatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThongTinDatLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(ThongTinDatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ThongTinDatLayout.createSequentialGroup()
                        .addComponent(txt_TuNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ThongTinDatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_DenNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(114, 114, 114))
        );
        ThongTinDatLayout.setVerticalGroup(
            ThongTinDatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThongTinDatLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(ThongTinDatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(6, 6, 6)
                .addGroup(ThongTinDatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_TuNgay, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(txt_DenNgay, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel1.add(ThongTinDat);
        ThongTinDat.setBounds(20, 60, 520, 100);

        jLabel14.setBackground(new java.awt.Color(255, 209, 84));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 209, 84));
        jLabel14.setText("Doanh Thu");
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel14.setName(""); // NOI18N
        jPanel1.add(jLabel14);
        jLabel14.setBounds(20, 20, 250, 32);

        btn_ThongKe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_ThongKe.setkEndColor(new java.awt.Color(255, 222, 89));
        btn_ThongKe.setkGradientFocus(250);
        btn_ThongKe.setkStartColor(new java.awt.Color(225, 176, 27));
        btn_ThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_ThongKeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_ThongKeMouseExited(evt);
            }
        });

        btnThongKe.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnThongKe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnThongKe.setText("Thống kê");
        btnThongKe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThongKe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThongKeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btn_ThongKeLayout = new javax.swing.GroupLayout(btn_ThongKe);
        btn_ThongKe.setLayout(btn_ThongKeLayout);
        btn_ThongKeLayout.setHorizontalGroup(
            btn_ThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
        );
        btn_ThongKeLayout.setVerticalGroup(
            btn_ThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_ThongKeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(btn_ThongKe);
        btn_ThongKe.setBounds(1080, 90, 140, 40);

        ThongTinDat1.setBackground(new java.awt.Color(0, 0, 0));
        ThongTinDat1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 209, 84), 2));
        ThongTinDat1.setOpaque(false);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Theo Quý");

        cb_TheoQuy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        cb_TheoQuy.setSelectedItem(null);
        cb_TheoQuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_TheoQuyActionPerformed(evt);
            }
        });

        cb_TheoNam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2020", "2021", "2022", "2023", "2024" }));
        cb_TheoNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_TheoNamActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Theo Năm");

        javax.swing.GroupLayout ThongTinDat1Layout = new javax.swing.GroupLayout(ThongTinDat1);
        ThongTinDat1.setLayout(ThongTinDat1Layout);
        ThongTinDat1Layout.setHorizontalGroup(
            ThongTinDat1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThongTinDat1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(ThongTinDat1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_TheoQuy, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(34, 34, 34)
                .addGroup(ThongTinDat1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_TheoNam, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        ThongTinDat1Layout.setVerticalGroup(
            ThongTinDat1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThongTinDat1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(ThongTinDat1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ThongTinDat1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_TheoNam, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ThongTinDat1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_TheoQuy, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel1.add(ThongTinDat1);
        ThongTinDat1.setBounds(570, 60, 460, 100);

        javax.swing.GroupLayout panel_ThongKeDoanhThuLayout = new javax.swing.GroupLayout(panel_ThongKeDoanhThu);
        panel_ThongKeDoanhThu.setLayout(panel_ThongKeDoanhThuLayout);
        panel_ThongKeDoanhThuLayout.setHorizontalGroup(
            panel_ThongKeDoanhThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ScrollChart, javax.swing.GroupLayout.DEFAULT_SIZE, 1240, Short.MAX_VALUE)
        );
        panel_ThongKeDoanhThuLayout.setVerticalGroup(
            panel_ThongKeDoanhThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_ThongKeDoanhThuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ScrollChart, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(panel_ThongKeDoanhThu);
        panel_ThongKeDoanhThu.setBounds(20, 190, 1240, 590);

        jPanel2.setOpaque(false);
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        label_Avatar.setMaximumSize(new java.awt.Dimension(45, 45));
        label_Avatar.setMinimumSize(new java.awt.Dimension(45, 45));
        label_Avatar.setPreferredSize(new java.awt.Dimension(45, 45));

        javax.swing.GroupLayout circlePanel1Layout = new javax.swing.GroupLayout(circlePanel1);
        circlePanel1.setLayout(circlePanel1Layout);
        circlePanel1Layout.setHorizontalGroup(
            circlePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(circlePanel1Layout.createSequentialGroup()
                .addComponent(label_Avatar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        circlePanel1Layout.setVerticalGroup(
            circlePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, circlePanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_Avatar, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setOpaque(false);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 209, 84));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Nguyễn Hoàng Sang");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(circlePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(circlePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(1020, 0, 260, 70);

        Backgroup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Backgroup.png"))); // NOI18N
        Backgroup.setPreferredSize(new java.awt.Dimension(1283, 803));
        jPanel1.add(Backgroup);
        Backgroup.setBounds(0, 0, 1283, 803);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1288, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1282, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 842, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ThongKeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ThongKeMouseEntered
        // TODO add your handling code here:
        btn_ThongKe.setkStartColor(new java.awt.Color(255, 225, 27));
        btn_ThongKe.setkEndColor(new java.awt.Color(255, 222, 89));
        btn_ThongKe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 1));
        btn_ThongKe.setBorder(null);
    }//GEN-LAST:event_btn_ThongKeMouseEntered

    private void btn_ThongKeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ThongKeMouseExited
        // TODO add your handling code here:
        btn_ThongKe.setkStartColor(new java.awt.Color(225, 176, 27));
        btn_ThongKe.setkEndColor(new java.awt.Color(255, 222, 89));
        btn_ThongKe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 1));
        btn_ThongKe.setBorder(null);
    }//GEN-LAST:event_btn_ThongKeMouseExited

    private void btnThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThongKeMouseClicked
        // TODO add your handling code here:
        updateBieuDo();
    }//GEN-LAST:event_btnThongKeMouseClicked

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
        new TrangCaNhan(nhanVien_DangSuDung).setVisible(true);
    }//GEN-LAST:event_jPanel2MouseClicked

    private void txt_TuNgayPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txt_TuNgayPropertyChange
        // TODO add your handling code here:
//        cb_TheoNam.setSelectedItem(null);
//        cb_TheoQuy.setSelectedItem(null);
    }//GEN-LAST:event_txt_TuNgayPropertyChange

    private void txt_DenNgayPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txt_DenNgayPropertyChange
        // TODO add your handling code here:
//        cb_TheoNam.setSelectedItem(null);
//        cb_TheoQuy.setSelectedItem(null);
    }//GEN-LAST:event_txt_DenNgayPropertyChange

    private void cb_TheoQuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_TheoQuyActionPerformed
        // TODO add your handling code here:
        txt_TuNgay.setDate(null);
        txt_DenNgay.setDate(null);
    }//GEN-LAST:event_cb_TheoQuyActionPerformed

    private void cb_TheoNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_TheoNamActionPerformed
        // TODO add your handling code here:
        txt_TuNgay.setDate(null);
        txt_DenNgay.setDate(null);
    }//GEN-LAST:event_cb_TheoNamActionPerformed

    private void updateBieuDo() {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

        Date ngayBatDau = null;
        Date ngayKetThuc = null;
        Map<Date, Date> result;
        if (cb_TheoNam.getSelectedIndex() != -1) {
            if (cb_TheoQuy.getSelectedItem() == null){
                result = getDateRange("5", cb_TheoNam.getSelectedItem().toString());
            }
            else
            {
                result = getDateRange(cb_TheoQuy.getSelectedItem().toString(), cb_TheoNam.getSelectedItem().toString());
            }
            try {
                ngayBatDau = sdf.parse(sdf.format(result.keySet().iterator().next()));
                ngayKetThuc = sdf.parse(sdf.format(result.values().iterator().next()));
                System.out.println(ngayBatDau);
                System.out.println(ngayKetThuc);

            } catch (ParseException ex) {
                Logger.getLogger(QuanLy_DoanhThu_GUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else 
        {
            try {
                ngayBatDau = sdf.parse(sdf.format(txt_TuNgay.getDate()));
                ngayKetThuc = sdf.parse(sdf.format(txt_DenNgay.getDate()));
            } catch (ParseException ex) {
                Logger.getLogger(QuanLy_DoanhThu_GUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        
        if (ngayBatDau == null && ngayKetThuc == null) {
            return;
        }

        ThongKe_BieuDoCotTheHienMucDoSuDungLoaiPhong barChart1 = new ThongKe_BieuDoCotTheHienMucDoSuDungLoaiPhong(ddpDAO.getDoanhThu(ngayBatDau, ngayKetThuc), ngayBatDau, ngayKetThuc);
        ThongKe_BieuDoCotTheHienMucDoSuDungDichVuTheoLoaiPhong barChart2
                = new ThongKe_BieuDoCotTheHienMucDoSuDungDichVuTheoLoaiPhong(ddpDAO.getDoanhThu(ngayBatDau, ngayKetThuc), ngayBatDau, ngayKetThuc);
        ThongKe_BieuDoCotTheHienMucDoSuDungDichVu barChart3
                = new ThongKe_BieuDoCotTheHienMucDoSuDungDichVu(ddpDAO.getDoanhThu(ngayBatDau, ngayKetThuc), ngayBatDau, ngayKetThuc);
        ThongKe_BieuDoTronTheHienPhanTramDoanhThuLoaiPhong pieChart1 = new ThongKe_BieuDoTronTheHienPhanTramDoanhThuLoaiPhong(
                ddpDAO.getDoanhThu(ngayBatDau, ngayKetThuc), ngayBatDau, ngayKetThuc
        );
        ThongKe_BieuDoTronTheHienPhanTramDoanhThuPhongVaDichVu pieChart2
                = new ThongKe_BieuDoTronTheHienPhanTramDoanhThuPhongVaDichVu(
                        ddpDAO.getDoanhThu(ngayBatDau, ngayKetThuc), ngayBatDau, ngayKetThuc
                );
        barChart1.setPreferredSize(new Dimension(1200, 585));
        barChart2.setPreferredSize(new Dimension(1200, 585));
        barChart3.setPreferredSize(new Dimension(1200, 585));

        pieChart1.setPreferredSize(new Dimension(1200, 585));
        pieChart2.setPreferredSize(new Dimension(1200, 585));

        chartPanel.removeAll();
        addChartToScrollPane(pieChart2);
        addChartToScrollPane(pieChart1);
        addChartToScrollPane(barChart1);
        addChartToScrollPane(barChart2);
        addChartToScrollPane(barChart3);
    }

    private Map<Date, Date> getDateRange(String qui, String nam) {
        Map<Date, Date> dateRange = new HashMap<>();

        // Chuyển đổi năm sang số nguyên
        int year = Integer.parseInt(nam) - 1900;
        Date startDate;
        Date endDate;

        switch (qui) {
            case "1":
                startDate = new Date(year, 0, 1);
                endDate = new Date(year, 2, 31);

                break;
            case "2":
                startDate = new Date(year, 3, 1);
                endDate = new Date(year, 5, 30);
                break;
            case "3":

                startDate = new Date(year, 6, 1);
                endDate = new Date(year, 8, 30);
                break;
            case "4":
                startDate = new Date(year, 9, 1);
                endDate = new Date(year, 11, 31);
                break;
            case "5":
                startDate = new Date(year, 0, 1);
                endDate = new Date(year, 11, 31);
                break;
            default:
                throw new IllegalArgumentException("Quý không hợp lệ: " + qui);
        }

        dateRange.put(startDate, endDate);

        return dateRange;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Backgroup;
    private javax.swing.JScrollPane ScrollChart;
    private javax.swing.JPanel ThongTinDat;
    private javax.swing.JPanel ThongTinDat1;
    private javax.swing.JLabel btnThongKe;
    private keeptoo.KGradientPanel btn_ThongKe;
    private javax.swing.JComboBox<String> cb_TheoNam;
    private javax.swing.JComboBox<String> cb_TheoQuy;
    private GUI.CirclePanel_Atatar circlePanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel label_Avatar;
    private javax.swing.JPanel panel_ThongKeDoanhThu;
    private com.toedter.calendar.JDateChooser txt_DenNgay;
    private com.toedter.calendar.JDateChooser txt_TuNgay;
    // End of variables declaration//GEN-END:variables
    private DonDatPhongDAO ddpDAO;
    private JPanel chartPanel;
}
