/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Functions.ImageScale;
import static GUI.DangNhap_GUI.database;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import model.DAO.NhanVienDAO;
import model.DTO.NhanVien;
import model.MongoDBConnection;

/**
 *
 * @author ASUS
 */
public class TrangCaNhan_DoiMatKhau extends javax.swing.JFrame {

    /**
     * Creates new form TrangCaNhan
     */
    private NhanVien nhanVien_DangSuDung;
    private ImageIcon password_hide;
    private ImageIcon password_show;
    public TrangCaNhan_DoiMatKhau(NhanVien nhanVien_DangSuDung) {
        this.nhanVien_DangSuDung = nhanVien_DangSuDung;
        initComponents();
        this.password_hide = new ImageScale().getScaledImage(MKCU_eye_label.getWidth(), MKCU_eye_label.getHeight(), "/images/hide-password.png");
        this.password_show = new ImageScale().getScaledImage(MKCU_eye_label.getWidth(), MKCU_eye_label.getHeight(), "/images/show-password.png");
        MKCuText.setEchoChar('*');
        MKMoiText.setEchoChar('*');
        XacNhanMKText.setEchoChar('*');
        MKCU_eye_label.setIcon(password_hide);
        MKMoi_eye_label.setIcon(password_hide);
        XacNhanMK_label.setIcon(password_hide);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_Thoat1 = new keeptoo.KGradientPanel();
        jLabel20 = new javax.swing.JLabel();
        btn_Thoat = new keeptoo.KGradientPanel();
        jLabel19 = new javax.swing.JLabel();
        MKMoiText = new javax.swing.JPasswordField();
        MKCuText = new javax.swing.JPasswordField();
        XacNhanMKText = new javax.swing.JPasswordField();
        MKCU_eye = new javax.swing.JPanel();
        MKCU_eye_label = new javax.swing.JLabel();
        MKCU_eye1 = new javax.swing.JPanel();
        MKMoi_eye_label = new javax.swing.JLabel();
        MKCU_eye2 = new javax.swing.JPanel();
        XacNhanMK_label = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(471, 477));
        getContentPane().setLayout(null);

        jPanel2.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 209, 84));
        jLabel2.setText("Mật khẩu cũ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 209, 84));
        jLabel3.setText("Mật khẩu mới");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 209, 84));
        jLabel4.setText("Xác nhận mật khẩu");

        btn_Thoat1.setkEndColor(new java.awt.Color(255, 222, 89));
        btn_Thoat1.setkGradientFocus(250);
        btn_Thoat1.setkStartColor(new java.awt.Color(225, 176, 27));
        btn_Thoat1.setPreferredSize(new java.awt.Dimension(210, 61));
        btn_Thoat1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_Thoat1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_Thoat1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_Thoat1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_Thoat1MousePressed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Hủy");
        jLabel20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel20.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout btn_Thoat1Layout = new javax.swing.GroupLayout(btn_Thoat1);
        btn_Thoat1.setLayout(btn_Thoat1Layout);
        btn_Thoat1Layout.setHorizontalGroup(
            btn_Thoat1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_Thoat1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );
        btn_Thoat1Layout.setVerticalGroup(
            btn_Thoat1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_Thoat1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btn_Thoat.setkEndColor(new java.awt.Color(255, 222, 89));
        btn_Thoat.setkGradientFocus(250);
        btn_Thoat.setkStartColor(new java.awt.Color(225, 176, 27));
        btn_Thoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ThoatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_ThoatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_ThoatMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_ThoatMousePressed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Xác nhận");
        jLabel19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel19.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout btn_ThoatLayout = new javax.swing.GroupLayout(btn_Thoat);
        btn_Thoat.setLayout(btn_ThoatLayout);
        btn_ThoatLayout.setHorizontalGroup(
            btn_ThoatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_ThoatLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );
        btn_ThoatLayout.setVerticalGroup(
            btn_ThoatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
        );

        MKCuText.setMinimumSize(new java.awt.Dimension(64, 28));
        MKCuText.setPreferredSize(new java.awt.Dimension(64, 28));

        XacNhanMKText.setMinimumSize(new java.awt.Dimension(64, 27));
        XacNhanMKText.setPreferredSize(new java.awt.Dimension(64, 27));

        MKCU_eye.setMaximumSize(new java.awt.Dimension(27, 27));
        MKCU_eye.setMinimumSize(new java.awt.Dimension(27, 27));
        MKCU_eye.setPreferredSize(new java.awt.Dimension(27, 27));

        MKCU_eye_label.setMaximumSize(new java.awt.Dimension(27, 27));
        MKCU_eye_label.setMinimumSize(new java.awt.Dimension(27, 27));
        MKCU_eye_label.setPreferredSize(new java.awt.Dimension(27, 27));
        MKCU_eye_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MKCU_eye_labelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout MKCU_eyeLayout = new javax.swing.GroupLayout(MKCU_eye);
        MKCU_eye.setLayout(MKCU_eyeLayout);
        MKCU_eyeLayout.setHorizontalGroup(
            MKCU_eyeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(MKCU_eyeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(MKCU_eyeLayout.createSequentialGroup()
                    .addComponent(MKCU_eye_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        MKCU_eyeLayout.setVerticalGroup(
            MKCU_eyeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(MKCU_eyeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(MKCU_eyeLayout.createSequentialGroup()
                    .addComponent(MKCU_eye_label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        MKCU_eye1.setMaximumSize(new java.awt.Dimension(27, 27));
        MKCU_eye1.setMinimumSize(new java.awt.Dimension(27, 27));
        MKCU_eye1.setPreferredSize(new java.awt.Dimension(27, 27));

        MKMoi_eye_label.setMaximumSize(new java.awt.Dimension(27, 27));
        MKMoi_eye_label.setMinimumSize(new java.awt.Dimension(27, 27));
        MKMoi_eye_label.setPreferredSize(new java.awt.Dimension(27, 27));
        MKMoi_eye_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MKCU_eye_labelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout MKCU_eye1Layout = new javax.swing.GroupLayout(MKCU_eye1);
        MKCU_eye1.setLayout(MKCU_eye1Layout);
        MKCU_eye1Layout.setHorizontalGroup(
            MKCU_eye1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 27, Short.MAX_VALUE)
            .addGroup(MKCU_eye1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(MKMoi_eye_label, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
        );
        MKCU_eye1Layout.setVerticalGroup(
            MKCU_eye1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(MKCU_eye1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MKCU_eye1Layout.createSequentialGroup()
                    .addComponent(MKMoi_eye_label, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        XacNhanMK_label.setMaximumSize(new java.awt.Dimension(27, 27));
        XacNhanMK_label.setMinimumSize(new java.awt.Dimension(27, 27));
        XacNhanMK_label.setPreferredSize(new java.awt.Dimension(27, 27));
        XacNhanMK_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MKCU_eye_labelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout MKCU_eye2Layout = new javax.swing.GroupLayout(MKCU_eye2);
        MKCU_eye2.setLayout(MKCU_eye2Layout);
        MKCU_eye2Layout.setHorizontalGroup(
            MKCU_eye2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 27, Short.MAX_VALUE)
            .addGroup(MKCU_eye2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(MKCU_eye2Layout.createSequentialGroup()
                    .addComponent(XacNhanMK_label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        MKCU_eye2Layout.setVerticalGroup(
            MKCU_eye2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 27, Short.MAX_VALUE)
            .addGroup(MKCU_eye2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(XacNhanMK_label, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MKCuText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(MKMoiText, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(XacNhanMKText, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, 0)
                                .addComponent(MKCU_eye2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(MKCU_eye1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(MKCU_eye, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(btn_Thoat, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(btn_Thoat1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(MKCU_eye, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(MKCuText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MKMoiText, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(MKCU_eye1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MKCU_eye2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(XacNhanMKText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Thoat1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Thoat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 470, 480);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Backgroup.png"))); // NOI18N
        jLabel1.setIconTextGap(0);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(1, 2, 470, 570);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ThoatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ThoatMouseEntered
        // TODO add your handling code here:
        btn_Thoat.setkStartColor(new java.awt.Color(255, 225, 27));
        btn_Thoat.setkEndColor(new java.awt.Color(255, 222, 89));
        btn_Thoat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 1));
        btn_Thoat.setBorder(null);
    }//GEN-LAST:event_btn_ThoatMouseEntered

    private void btn_ThoatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ThoatMouseExited
        // TODO add your handling code here:
        // TODO add your handling code here:
        btn_Thoat.setkStartColor(new java.awt.Color(225, 176, 27));
        btn_Thoat.setkEndColor(new java.awt.Color(255, 222, 89));
        btn_Thoat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 1));
        btn_Thoat.setBorder(null);
    }//GEN-LAST:event_btn_ThoatMouseExited

    private void btn_ThoatMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ThoatMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ThoatMousePressed

    private void btn_Thoat1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Thoat1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Thoat1MouseEntered

    private void btn_Thoat1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Thoat1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Thoat1MouseExited

    private void btn_Thoat1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Thoat1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Thoat1MousePressed

    private void btn_ThoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ThoatMouseClicked
        // TODO add your handling code here:
        String mkCu = MKCuText.getText().trim();
        String mkMoi = MKMoiText.getText().trim();
        String xacNhanMK = XacNhanMKText.getText().trim();
        if(mkCu.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Chưa nhập mật khẩu cũ");
        }
        if(!mkCu.equals(nhanVien_DangSuDung.getMatKhau())) {
            JOptionPane.showMessageDialog(rootPane, "Mật khẩu không đúng!");
            return;
        } 
        if(mkMoi.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Chưa nhập mật khẩu mới!");
            return;
        }
        if(xacNhanMK.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Chưa xác nhận mật khẩu!");
            return;
        }
        if(!xacNhanMK.equals(mkMoi)) {
            JOptionPane.showMessageDialog(rootPane, "Mật khẩu không khớp!");
            return;
        }
        {
            MongoDBConnection.connection();
            database = MongoDBConnection.getDatabase();
            NhanVien nv = nhanVien_DangSuDung;
            nv.setMatKhau(mkMoi);
            if (new NhanVienDAO(database).updateNhanVien(nv)){
                JOptionPane.showMessageDialog(rootPane, "Đổi mật khẩu thành công!");
                this.dispose();
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Đổi mật khẩu thất bại!");
            }
        }
        
    }//GEN-LAST:event_btn_ThoatMouseClicked

    private void btn_Thoat1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Thoat1MouseClicked
        // TODO add your handling code here:
        btn_Thoat.getParent().getParent().getParent().getParent().getParent().setVisible(false);
    }//GEN-LAST:event_btn_Thoat1MouseClicked
    private void showHidePwrd(JLabel label, JPasswordField textField) {
        if(textField.getEchoChar() == '*') {
            label.setIcon(password_show);
            textField.setEchoChar((char) 0);
        } else {
            label.setIcon(password_hide);
            textField.setEchoChar('*');
        }
    }
    private void MKCU_eye_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MKCU_eye_labelMouseClicked
        // TODO add your handling code here:
        Object o = evt.getSource();
        if(o.equals(MKCU_eye_label)) {
            showHidePwrd(MKCU_eye_label, MKCuText);
        }
        if(o.equals(MKMoi_eye_label)) {
            showHidePwrd(MKMoi_eye_label, MKMoiText);
        }
        if(o.equals(XacNhanMK_label)) {
            showHidePwrd(MKCU_eye_label, XacNhanMKText);
        }
    }//GEN-LAST:event_MKCU_eye_labelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrangCaNhan_DoiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrangCaNhan_DoiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrangCaNhan_DoiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrangCaNhan_DoiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MKCU_eye;
    private javax.swing.JPanel MKCU_eye1;
    private javax.swing.JPanel MKCU_eye2;
    private javax.swing.JLabel MKCU_eye_label;
    private javax.swing.JPasswordField MKCuText;
    private javax.swing.JPasswordField MKMoiText;
    private javax.swing.JLabel MKMoi_eye_label;
    private javax.swing.JPasswordField XacNhanMKText;
    private javax.swing.JLabel XacNhanMK_label;
    private keeptoo.KGradientPanel btn_Thoat;
    private keeptoo.KGradientPanel btn_Thoat1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
